server:
  port: 8087
mybatis:
  typeAliasesPackage: com.llg.springbootredis.entity
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootredis?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
